import RaceService from "../../../lib/class/RaceService";
import { RaceServiceProps } from "../../../lib/interfaces/IRaceService";

export async function POST(request: Request) {
	const raceData = await request.json();
	// Ensure 'id' is present; generate one if needed
	const raceDataWithId: RaceServiceProps = {
		id: raceData.id || "", //id will be generated by the database
		...raceData,
	};
	const raceService = new RaceService(raceDataWithId);
	const newRace = await raceService.saveRace();
	return new Response(JSON.stringify(newRace), { status: 201 });
}
export async function GET(request : Request) {
	const raceService = RaceService.getAllRaces();
	console.log(raceService);
	return new Response(JSON.stringify(raceService), { status: 200 });
}
