import dbConnect from "../mongodb";
import  {UserServiceProps}  from "../interfaces/IUserService";


class UserService {
	id: string;
	name: string;
	mail: string;
	interests: string[];

	constructor(arg: string | UserServiceProps) {
		if (typeof arg === "string") {
			// Construct from id only
			this.id = arg;
			this.name = "";
			this.mail = "";
			this.interests = [];
			this.getUserById(arg);
		} else {
			// Construct from full props
			this.id = arg.id;
			this.name = arg.name;
			this.mail = arg.mail;
			this.interests = arg.interests || [];
		}
	}
	private async refreshUser(user: UserServiceProps) {
		this.id = user.id;
		this.name = user.name;
		this.mail = user.mail;
		this.interests = user.interests || [];
	}

	async getUserById(id: string) {
		const db = await dbConnect();
		const res = await db.collection("users").findOne({ _id: id });
		this.refreshUser(res as UserServiceProps);
	}
	async saveUser() {
		const db = await dbConnect();
		const userData: UserServiceProps = {
			id: this.id || "", // id will be generated by the database
			name: this.name,
			mail: this.mail,
			interests: this.interests
		};
		const result = await db.collection("users").insertOne(userData);
		if (result.acknowledged) {
			this.id = result.insertedId.toString();
			this.refreshUser(userData);
			return this;
		}else {
			throw new Error("Failed to save user");
		}
	}
	async updateUser(userData: UserServiceProps) {
		const db = await dbConnect();
		const updatedData: UserServiceProps = {
			id: userData.id,
			name: userData.name,
			mail: userData.mail,
			interests: userData.interests
		};
		const result = await db.collection("users").updateOne({ _id: this.id }, { $set: updatedData });
		if (result.acknowledged) {
			this.refreshUser(updatedData);
			return this;
		}else {
			throw new Error("Failed to update user");
		}
	}
	async deleteUser() {
		const db = await dbConnect();
		const result = await db.collection("users").deleteOne({ _id: this.id });
		if (result.acknowledged) {
			return { success: true };
		} else {
			throw new Error("Failed to delete user");
		}
	}

	// Getters
	getId(): string {
		return this.id;
	}

	getName(): string {
		return this.name;
	}

	getMail(): string {
		return this.mail;
	}

	getInterests(): string[] {
		return this.interests;
	}

	// Setters
	setId(id: string): void {
		this.id = id;
	}

	setName(name: string): void {
		this.name = name;
	}

	setMail(mail: string): void {
		this.mail = mail;
	}

	setInterests(interests: string[]): void {
		this.interests = interests;
	}
}

export default UserService;
